### ISSUE TITLE
Will stepping feature be supported?

### ISSUE THREAD

**Issue by maoqxxmm** [react-grid-layout/react-resizable#176]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [ ] Bug
- [x] Feature Request
- [ ] Question

### Problem Report

It's a common feature in calendar apps. When the user resizes a task to change the due date, the task will stepply change it's width or height(maybe 20 px everytime). But react-resizable seems not able to support this feature. So, is it in a roadmap?

**Comment by STRML** [comment]
The demo has an example of this feature already.

**Comment by maoqxxmm** [comment]
> The demo has an example of this feature already.

Oh, it's my fault for not checking the demo.😢
