### ISSUE TITLE
Handle resize components but not trigger resize event

### ISSUE THREAD

**Issue by gaecoli** [react-grid-layout/react-resizable#194]
### Thanks for opening an issue!

Please select the type of issue you're reporting. For questions.

- [x] Bug
- [ ] Feature Request
- [ x] Question

> Please describe the problem here.
when i handle to resize content, but why this component not trigger resize event? maybe this is a bug? or problem?

#### System Info

Node Version: 8.6.0
Browser: chrome
OS: Mac OS

**Comment by edemen** [comment]
I noticed sometimes that you need to move the cursor really far away to start triggering the `onResize` event, even though `onResizeStart` and `onResizeStop` trigger correctly.

**Comment by linxianxi** [comment]
same, any update?

**Comment by linxianxi** [comment]
> 我注意到有时您需要将光标移到很远的地方才能开始触发事件`onResize`，即使`onResizeStart`并`onResizeStop`正确触发。

same, any update? How to solve it?
