### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by NicolaLovo** [react-grid-layout/react-resizable#205]
## Add typescript support for ts users and better usage experience

When programming in typescript(but also javascript) having the types definitions allows for a better user experience for developing. I appreciate a lot your component and I would be grateful if you could introduce typescript support, it would boost our productivity.
Thank you!

**Comment by STRML** [comment]
Use https://www.npmjs.com/package/@types/react-resizable

**Comment by NicolaLovo** [comment]
Thanks mate!
