### ISSUE TITLE
Possible to move the handle to the upper left corner?

### ISSUE THREAD

**Issue by Slapbox** [react-grid-layout/react-resizable#70]
Is this possible via an undocumented method? If not, do you think it would be as easy as forking and changing a few values, or would it be a significant undertaking?

Thanks very much for the cool repo.

**Comment by sanohin** [comment]
Why don't you just change the styles? `.react-resizable-handle` is the class you need

**Comment by Slapbox** [comment]
@sanohin I'm pretty sure I tried that. The box still expands in the same direction though if I'm not mistaken. It's been a while, can't quite recall.

**Comment by don-p** [comment]
+1 for this.

I believe what's being asked is not just to move the position of the handle to the left side (either top or bottom), but also to change the direction of the expansion/resizing.

Please provide some guidance/information on what's required.

**Comment by FatherNelson** [comment]
+1 for this. 

I want to be able to dynamically change the direction of expansion and was looking for some guidance to even do such in a single direction

**Comment by sag1v** [comment]
I think this feature requires some sort of `rtl` support. 
like:
`resizeDirection: ltr` -> this is the current behavior, from left to right
It would be nice to have the opposite 
`resizeDirection: rtl` -> from right to left

Note that this is not the position of the handle element but the direction of the mouse.

**Comment by nichita-pasecinic** [comment]
+1

**Comment by Vivek377** [comment]
+1
how to make it resizable from all sides? Please provide some guidance.

**Comment by STRML** [comment]
Use the base resizable element and move the css styles yourself. We do this in react-grid-layout, for instance.
